pipelines:
  default:
    - step:
        name: Sync to Repository B
        script:
          - git clone https://$BITBUCKET_USERNAME:$BITBUCKET_PASSWORD@bitbucket.org/synv09/repositorydestination.git
          - git remote add upstream https://$BITBUCKET_USERNAME:$BITBUCKET_PASSWORD@bitbucket.org/synv09/repositorysource.git
          - git fetch upstream
          - git merge upstream/main
          - git push origin main