pipelines:
  pull-requests:
    '**':
      - step:
          name: Sync PR to repo-dich
          script:
            - git config --global user.email "hoangpham19112002@gmail.com"
            - git config --global user.name "hoangpham1911"
            - git clone https://<username>:<app-password>https://bitbucket.org/synv09/repositorysource.git/
            - cd repositorysource
            - git remote add repo-dich https://<username>:<app-password>https://hoangpham19112002@bitbucket.org/synv09/repositorydestination.git
            - git fetch repo-dich
            - git checkout $BITBUCKET_PR_DESTINATION_BRANCH
            - git pull origin $BITBUCKET_PR_DESTINATION_BRANCH
            - git merge origin/$BITBUCKET_PR_SOURCE_BRANCH
            - git push repo-dich $BITBUCKET_PR_DESTINATION_BRANCH
