pipelines:
  pull-requests:
    '**':
      - step:
          name: Sync PR to RepositoryDestination
          script:
            - mkdir -p ~/.ssh
            - echo -e "Host bitbucket.org\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            - echo $SSH_KEY | base64 --decode > ~/.ssh/id_rsa
            - chmod 600 ~/.ssh/id_rsa
            - eval "$(ssh-agent -s)"
            - ssh-add ~/.ssh/id_rsa
            - git clone git@bitbucket.org:synv09/repositorysource.git RepositorySource
            - cd RepositorySource
            - git remote add RepositoryDestination git@bitbucket.org:synv09/repositorydestination.git
            - git fetch RepositoryDestination
            - git checkout $BITBUCKET_PR_DESTINATION_BRANCH
            - git pull origin $BITBUCKET_PR_DESTINATION_BRANCH
            - git merge origin/$BITBUCKET_PR_SOURCE_BRANCH
            - git push RepositoryDestination $BITBUCKET_PR_DESTINATION_BRANCH
