pipelines:
  branches:
    main:
      - step:
          name: Sync to RepositoryB
          script:
            - git config --global user.email "hoangpham19112002@gmail.com"
            - git config --global user.name "hoangpham1911"
            - git clone https://hoangpham19112002@bitbucket.org/synv09/repositorydestination.git
            - cd repositoryA
            - git remote add repoB https://hoangpham19112002@bitbucket.org/synv09/repositorydestination.git
            - git push repoB main
