pipelines:
  default:
    - step:
        name: Sync to Repository B
        script:
          - git clone https://hoangpham19112002@bitbucket.org/synv09/repositorydestination.git
          - cd repositoryB
          - git remote add upstream https://hoangpham19112002@bitbucket.org/synv09/repositorysource.git
          - git fetch upstream
          - git merge upstream/main
          - git push