pipelines:
  branches:
    main:
      - step:
          name: Sync to RepositoryB
          script:
            # Tạo thư mục ~/.ssh và thiết lập quyền cho SSH Private Key
            - mkdir -p ~/.ssh
            - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            - chmod 600 ~/.ssh/id_rsa
            - ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts

            # Kiểm tra SSH key đã được sử dụng đúng cách
            - ssh -T git@bitbucket.org || exit 1

            # Cấu hình Git
            - git config --global user.email "hoangpham19112002@gmail.com"
            - git config --global user.name "hoangpham1911"

            # Clone repo A bằng SSH
            - git clone git@bitbucket.org:synv09/repositorysource.git
            - cd repositorysource

            # Thêm remote repo B bằng SSH
            - git remote add testbitbu git@bitbucket.org:hoangvjp129/testbitbu.git

            # Fetch các thay đổi từ repo B
            - git fetch testbitbu

            # Merge các thay đổi từ repo A vào repo B
            - git merge testbitbu/main || exit 1

            # Đẩy các thay đổi lên repo B
            - git push testbitbu main
