pipelines:
  branches:
    main:
      - step:
          name: Sync to RepositoryB
          script:
            # Tạo thư mục ~/.ssh và thiết lập quyền nếu chưa có
            - mkdir -p ~/.ssh
            - chmod 700 ~/.ssh

            # Thiết lập quyền cho các SSH Private Key có sẵn
            - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            - chmod 600 ~/.ssh/id_rsa

            # Đảm bảo bitbucket.org được thêm vào known_hosts
            - ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts

            # Khởi động SSH agent
            - eval "$(ssh-agent -s)"

            # Cấu hình Git
            - git config --global user.email "hoangpham19112002@gmail.com"
            - git config --global user.name "hoangpham1911"

            # Clone repo A bằng SSH (repo A sẽ dùng id_rsa)
            - git clone git@bitbucket.org:synv09/repositorysource.git
            - cd repositorysource


            # Thêm repo B như một remote
            - git remote add RepoB git@github.com:hoangPham1911/RepoB.git

            # Fetch các thay đổi từ repo B
            - git fetch RepoB main

            # Merge các thay đổi từ repo B vào repo A
            - git merge RepoB/main --allow-unrelated-histories || echo "Không có thay đổi để merge" # Xử lý trường hợp không có gì để merge

            # Đẩy các thay đổi lên repo B
            - git push --force RepoB main