pipelines:
  branches:
    main:
      - step:
          name: Sync to RepositoryB
          script:
            # Tạo thư mục ~/.ssh nếu chưa có và thiết lập quyền cho SSH Private Key
            - mkdir -p ~/.ssh
            - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            - echo "$SSH_PRIVATE_KEY_TWO" > ~/.ssh/id_rsa_two
            - chmod 600 ~/.ssh/id_rsa ~/.ssh/id_rsa_two

            # Đảm bảo bitbucket.org được thêm vào known_hosts
            - ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts

            # Cấu hình Git
            - git config --global user.email "hoangpham19112002@gmail.com"
            - git config --global user.name "hoangpham1911"

            # Clone repoA (repo A sẽ dùng id_rsa)
            - git clone git@bitbucket.org:synv09/repositorysource.git repoA
            - cd repoA

            # Kiểm tra xem remote origin đã tồn tại chưa
            - if git remote get-url origin > /dev/null 2>&1; then
                echo "Remote origin already exists, updating URL...";
                git remote set-url origin git@bitbucket.org:hoangvjp129/testbitbu.git;
              else
                echo "Adding remote origin...";
                git remote set-url origin git@bitbucket.org:hoangvjp129/testbitbu.git;
              fi

            # Fetch và merge các thay đổi từ origin vào repoA
            - git fetch origin main
            - git merge origin/main --allow-unrelated-histories

            # Đẩy các thay đổi từ repoA lên origin
            - git push origin main
