pipelines:
  pull-requests:
    '**':
      - step:
          name: Sync PR to RepositoryDestination
          script:
            - git config --global user.email "hoangpham19112002@gmail.com"
            - git config --global user.name "hoangpham1911"
            - git clone https://hoangpham1911:ATBBEKD2KPYxSm2yT4xzBgURmRf9D19AC1FE@bitbucket.org/synv09/repositorysource.git RepositorySource
            - cd RepositorySource
            - git remote add RepositoryDestination https://hoangpham1911:ATBBEKD2KPYxSm2yT4xzBgURmRf9D19AC1FE@bitbucket.org/synv09/repositorydestination.git
            - git fetch RepositoryDestination
            - git checkout $BITBUCKET_PR_DESTINATION_BRANCH
            - git pull origin $BITBUCKET_PR_DESTINATION_BRANCH
            - git merge origin/$BITBUCKET_PR_SOURCE_BRANCH
            - git push RepositoryDestination $BITBUCKET_PR_DESTINATION_BRANCH
